version: '3'
services:
  backend:
    build: .
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chatwizard
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: